/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as PaymentDemoBookingIdRouteImport } from './routes/payment-demo.$bookingId'
import { Route as ApiPublicPaymentDemoBookingIdRouteImport } from './routes/api/public/payment-demo.$bookingId'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDemoBookingIdRoute = PaymentDemoBookingIdRouteImport.update({
  id: '/payment-demo/$bookingId',
  path: '/payment-demo/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentDemoBookingIdRoute =
  ApiPublicPaymentDemoBookingIdRouteImport.update({
    id: '/api/public/payment-demo/$bookingId',
    path: '/api/public/payment-demo/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/payment-demo/$bookingId': typeof PaymentDemoBookingIdRoute
  '/api/public/payment-demo/$bookingId': typeof ApiPublicPaymentDemoBookingIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/payment-demo/$bookingId': typeof PaymentDemoBookingIdRoute
  '/api/public/payment-demo/$bookingId': typeof ApiPublicPaymentDemoBookingIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/payment-demo/$bookingId': typeof PaymentDemoBookingIdRoute
  '/api/public/payment-demo/$bookingId': typeof ApiPublicPaymentDemoBookingIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/owner'
    | '/auth/callback'
    | '/payment-demo/$bookingId'
    | '/api/public/payment-demo/$bookingId'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/owner'
    | '/auth/callback'
    | '/payment-demo/$bookingId'
    | '/api/public/payment-demo/$bookingId'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/_authenticated/owner'
    | '/auth_/callback'
    | '/payment-demo/$bookingId'
    | '/api/public/payment-demo/$bookingId'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PaymentDemoBookingIdRoute: typeof PaymentDemoBookingIdRoute
  ApiPublicPaymentDemoBookingIdRoute: typeof ApiPublicPaymentDemoBookingIdRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-demo/$bookingId': {
      id: '/payment-demo/$bookingId'
      path: '/payment-demo/$bookingId'
      fullPath: '/payment-demo/$bookingId'
      preLoaderRoute: typeof PaymentDemoBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-demo/$bookingId': {
      id: '/api/public/payment-demo/$bookingId'
      path: '/api/public/payment-demo/$bookingId'
      fullPath: '/api/public/payment-demo/$bookingId'
      preLoaderRoute: typeof ApiPublicPaymentDemoBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PaymentDemoBookingIdRoute: PaymentDemoBookingIdRoute,
  ApiPublicPaymentDemoBookingIdRoute: ApiPublicPaymentDemoBookingIdRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
