import type { BusinessConfig } from "./types";

export const defaultBusiness: BusinessConfig = {
  id: "ember-thread",
  name: "Ember & Thread",
  archetype: "Tattoo studio",
  tagline: "Fine line, blackwork and cover-ups. Booked properly, once.",
  location: "Ostergatan 14, Malmo",
  policies: {
    currency: "EUR",
    leadTimeDays: 3,
    horizonDays: 90,
    autoApproveUnder: 900,
    autoApproveMaxDuration: 300,
    cancellationHours: 48,
    reviewNote:
      "Anything large, on tricky placement, or covering old work gets a quick look from Ines before it is confirmed.",
  },
  services: [
    {
      id: "tattoo",
      name: "Custom tattoo",
      blurb: "Original design, drawn for you and tattooed in one or more sittings.",
      basePrice: 180,
      baseDuration: 90,
      depositPercent: 20,
      questions: [
        {
          id: "size",
          label: "Roughly how big is the piece?",
          help: "Longest edge. An estimate is fine — we confirm at the studio.",
          type: "scale",
          min: 3,
          max: 40,
          step: 1,
          unit: "cm",
          pricePerUnit: 16,
          durationPerUnit: 9,
        },
        {
          id: "style",
          label: "What style are you after?",
          type: "single",
          options: [
            {
              id: "fineline",
              label: "Fine line",
              hint: "Delicate, single-needle work",
              requiresSkills: ["fineline"],
            },
            {
              id: "blackwork",
              label: "Blackwork",
              hint: "Bold, solid black shapes",
              priceFactor: 1.1,
              durationFactor: 1.15,
              requiresSkills: ["blackwork"],
            },
            {
              id: "colour",
              label: "Colour / illustrative",
              hint: "Layered colour packing",
              priceFactor: 1.35,
              durationFactor: 1.4,
              requiresSkills: ["colour"],
            },
            {
              id: "lettering",
              label: "Lettering",
              hint: "Script or type-led",
              priceFactor: 0.95,
              requiresSkills: ["lettering"],
            },
          ],
        },
        {
          id: "placement",
          label: "Where on the body?",
          type: "single",
          options: [
            { id: "arm", label: "Arm or leg" },
            { id: "back", label: "Back or chest", durationFactor: 1.15 },
            {
              id: "hand",
              label: "Hand, neck or face",
              hint: "Needs a conversation first",
              priceDelta: 60,
              requiresReview: true,
              requiresSkills: ["exposed-placement"],
            },
            { id: "ribs", label: "Ribs, hip or sternum", priceFactor: 1.15, durationFactor: 1.2 },
          ],
        },
        {
          id: "coverup",
          label: "Is this covering or reworking existing ink?",
          type: "boolean",
          options: [
            {
              id: "yes",
              label: "Yes",
              priceFactor: 1.3,
              durationFactor: 1.35,
              requiresReview: true,
              requiresPhotos: true,
              requiresSkills: ["coverup"],
            },
            { id: "no", label: "No, fresh skin" },
          ],
        },
        {
          id: "extras",
          label: "Anything to add?",
          type: "multi",
          optional: true,
          options: [
            { id: "design", label: "Extra design round", hint: "A second sketch pass", priceDelta: 70 },
            { id: "evening", label: "Evening sitting", hint: "After 18:00", priceDelta: 40 },
            { id: "numbing", label: "Numbing cream", priceDelta: 25, durationDelta: 20 },
            {
              id: "companion",
              label: "Bring someone with me",
              hint: "Small studio — we just need to know",
            },
          ],
        },
        {
          id: "firsttime",
          label: "Is this your first tattoo?",
          type: "boolean",
          options: [
            { id: "yes", label: "Yes", durationDelta: 20 },
            { id: "no", label: "No" },
          ],
        },
        {
          id: "reference",
          label: "Describe the idea",
          help: "A sentence or two. Reference images can be sent after booking.",
          type: "text",
        },
      ],
    },
    {
      id: "flash",
      name: "Flash piece",
      blurb: "Pick a ready-made design from the studio sheet. Quick and fixed price.",
      basePrice: 140,
      baseDuration: 60,
      depositPercent: 25,
      questions: [
        {
          id: "sheet",
          label: "Which sheet caught your eye?",
          type: "single",
          options: [
            { id: "botanical", label: "Botanical", requiresSkills: ["fineline"] },
            { id: "folk", label: "Folk & symbols", priceDelta: 20, requiresSkills: ["blackwork"] },
            { id: "type", label: "Type & numerals", requiresSkills: ["lettering"] },
          ],
        },
        {
          id: "sizeflash",
          label: "Size",
          type: "single",
          options: [
            { id: "s", label: "Small (up to 7cm)" },
            { id: "m", label: "Medium (7–14cm)", priceDelta: 70, durationDelta: 30 },
            { id: "l", label: "Large (14cm+)", priceDelta: 160, durationDelta: 75 },
          ],
        },
        {
          id: "placementflash",
          label: "Placement",
          type: "single",
          options: [
            { id: "arm", label: "Arm or leg" },
            { id: "torso", label: "Torso", durationFactor: 1.1 },
            {
              id: "hand",
              label: "Hand or neck",
              priceDelta: 50,
              requiresReview: true,
              requiresSkills: ["exposed-placement"],
            },
          ],
        },
      ],
    },
    {
      id: "consult",
      name: "Consultation",
      blurb: "Thirty minutes to talk through a bigger project. Free, and counts toward your deposit.",
      basePrice: 0,
      baseDuration: 30,
      depositPercent: 0,
      questions: [
        {
          id: "scope",
          label: "What are you thinking about?",
          type: "single",
          options: [
            { id: "sleeve", label: "Sleeve or large project", requiresReview: true },
            { id: "coverup", label: "Cover-up", requiresPhotos: true, requiresSkills: ["coverup"] },
            { id: "unsure", label: "Still figuring it out" },
          ],
        },
        {
          id: "notes",
          label: "Anything we should know beforehand?",
          type: "text",
          optional: true,
        },
      ],
    },
  ],
  team: [
    {
      id: "ines",
      name: "Ines Marrow",
      role: "Owner, blackwork & cover-ups",
      initials: "IM",
      skills: ["blackwork", "coverup", "lettering", "exposed-placement", "fineline"],
      days: [2, 3, 4, 5],
      start: "11:00",
      end: "19:00",
      maxSession: 360,
    },
    {
      id: "tove",
      name: "Tove Lind",
      role: "Fine line & botanical",
      initials: "TL",
      skills: ["fineline", "lettering"],
      days: [1, 2, 4, 6],
      start: "10:00",
      end: "17:00",
      maxSession: 240,
    },
    {
      id: "rafa",
      name: "Rafa Osei",
      role: "Colour & illustrative",
      initials: "RO",
      skills: ["colour", "fineline", "blackwork"],
      days: [3, 4, 5, 6],
      start: "12:00",
      end: "20:00",
      maxSession: 300,
    },
  ],
};

export const otherArchetypes = [
  {
    name: "Pet groomer",
    question: "Coat type, matting, temperament",
    effect: "Matted double coat adds 45 min and routes to the senior groomer",
  },
  {
    name: "Photographer",
    question: "Shoot type, location, people count",
    effect: "Off-site shoots add travel time and a second shooter to the quote",
  },
  {
    name: "Contractor",
    question: "Room size, access, materials",
    effect: "No lift access flags the job for a site visit before pricing",
  },
  {
    name: "Beauty studio",
    question: "Hair length, existing colour, allergies",
    effect: "Colour correction becomes a two-part booking with a patch test",
  },
];
